version: '3.8'

services:
  backend:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      - DOMAIN=localhost
      - BACKEND_CORS_ORIGINS=http://localhost,http://localhost:5173,https://localhost,https://localhost:5173
      - SECRET_KEY=test
      - POSTGRES_SERVER=host.docker.internal
      - POSTGRES_PORT=5432
      - POSTGRES_DB=uptime_monitoring
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    command: ["uvicorn", "backend.app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]